baseURL = "https://marcus.se.net"
languageCode = "en-us"
title = "Marcus Olsson"
theme = "minimal-garden"

[params]
  logo = "avatar.png"
  subtitle = "Software Creative and Educator"
  description = "Marcus Olsson is a Developer Advocate at Grafana Labs."
  author = "Marcus Olsson"
  twitter = "marcusolsson"
  github = "marcusolsson"
	linkedin = "marcusolsson1"

[permalinks]
	writing = ":filename"

[markup]
  [markup.highlight]
    style = "dracula"
