name = "minimal"
license = "MIT"
licenselink = "https://github.com/marcusolsson/hugo-minimal/LICENSE"
description = ""
homepage = "https://github.com/marcusolsson/hugo-minimal"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Marcus Olsson"
  homepage = "https://marcus.se.net"

